### ISSUE TITLE
Button alignment

### ISSUE THREAD

**Issue by lethosor** [Lazy-Newb-Pack/lazynewbpack.com#1]
I'm not sure how these look in other browsers, but this is what `/linux` looks like in Chrome:
![screen shot 2014-12-31 at 5 37 44 pm](https://cloud.githubusercontent.com/assets/3719547/5591013/e0d6d8f8-9113-11e4-9d21-1a578376fed6.png)
Removing the `fa-2x` class from the download icons improves the alignment, but the resulting buttons are rather small:
![screen shot 2014-12-31 at 5 39 05 pm](https://cloud.githubusercontent.com/assets/3719547/5591017/f3290c38-9113-11e4-9191-4f5169462e11.png)

**Comment by BeauBouchard** [comment]
I changed the button icon sizes to be fa-lg, and removed repeated text. :D I made this page in a rush and it really needs a better look. :D feel free to fork if you want to make any changes. Its really a dull page, but clean.

**Comment by lethosor** [comment]
Looks good to me, although it doesn't seem to have deployed yet (it could simply be cached on my end). The `/assets` folder is missing from this repo, which makes it difficult to test certain changes without copying over each file in it, although I'm not necessarily opposed to leaving out binary assets.

**Comment by BeauBouchard** [comment]
I am going to add the assets folder to the repo to make it easier for other people to test, it mostly contains [boot strap js binary](http://getbootstrap.com/javascript/) and  [Awesome font](http://fortawesome.github.io/Font-Awesome/) css stuff.  :beers:
