### ISSUE TITLE
default Linux link broken 

### ISSUE THREAD

**Issue by oskanberg** [Lazy-Newb-Pack/lazynewbpack.com#9]
'Default' linux d/l option links to: http://goo.gl/Na6v0x/

Which, as far as I can tell, only returns a 404.

**Comment by BeauBouchard** [comment]
yep I accidentally added a forward slash to the link. It should be "[http://goo.gl/Na6v0x](http://goo.gl/Na6v0x)" But google also blocked it again and auto-marked it as spam.

**Comment by BeauBouchard** [comment]
I am not sure if more people "request a review" makes a difference or not. But in the mean time you can download the packages at 

[http://lazynewbpack.com/linux/04024/download/x64/04024r3-x64.zip](http://lazynewbpack.com/linux/04024/download/x64/04024r3-x64.zip)
and
[http://lazynewbpack.com/linux/04024/download/i686/04024r3-i686.zip](http://lazynewbpack.com/linux/04024/download/i686/04024r3-i686.zip), however I expect the google links to be working within the next day or so, that is what happened last time. And do not want to change all the links thrice again.

**Comment by lethosor** [comment]
From http://goo.gl/policy.html:

> Do not use goo.gl for URLs that are either executable/package files (like .apk, .dmg, .exe, .zip, etc.)

**Comment by BeauBouchard** [comment]
converting to .tar.gz. just kidding, i will just have to get the information from the logs i guess, or use google analytics events
